/* Loopback-only semantic rendering tests; intercepted synthetic reports only. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const origin=process.env.REPORT_TEST_ORIGIN||'http://127.0.0.1:8899';
assert.ok(['localhost','127.0.0.1'].includes(new URL(origin).hostname));
const evidence=process.env.REPORT_SECTION_EVIDENCE||'/private/tmp/bwm-report-sections';fs.mkdirSync(evidence,{recursive:true});
const dates=[{label:'Synthetic SST — observed, not forecast',date:'2026-09-18T08:00:00Z'},{label:'Synthetic CHL — gap-filled analysis',date:'2026-09-17T00:00:00Z'}];
const text='SYNTHETIC TEST — NOT FOR NAVIGATION\nYour selected radius is 100 nautical miles.\n\nSea-surface temperature\n28.40 °C; range 27.9–28.8 °C. Approximate position 25.1°N, 79.8°W.\nSource time: 2026-09-18T08:00:00Z. Quality: partial coverage.\n\nChlorophyll\n0.023 mg/m³. Gap-filled analysis; cloudy pixels are not direct observations.\n\nCurrents\n0.4 m/s toward 270°. Missing samples remain unavailable.\n\nWeather forecast\nWind: 12 knots. Pressure: 1013.2 hPa. Forecast updated: 2026-09-18T06:00:00Z.\n\nSargassum\nInformation is unavailable. This does not establish absence.\n\nWaves\nData are unavailable for this update.\n\nUnrecognized producer note\nKeep this line and its spacing  exactly.\n\nA planning tool, not a navigation system.\n';
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'chrome'});let checks=0;try{for(const width of [320,390,820,1440]){const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let bodyText=text;let unavailable=false;
await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin!==new URL(origin).origin)return route.abort();assert.ok(['GET','HEAD'].includes(route.request().method()));if(u.pathname==='/api/reports/catalog')return route.fulfill({json:{destinations:[{id:'miami-fl',name:'Miami',admin:'FL',available:true}]}});if(u.pathname==='/api/reports/report')return unavailable?route.fulfill({status:503,json:{error:'Synthetic failure'}}):route.fulfill({json:{destinationId:'miami-fl',title:'Miami, FL',status:'available',reportDate:'2026-09-18T16:10:00Z',radiusNm:100,sourceDates:dates,text:bodyText}});return route.continue();});
await page.clock.install({time:new Date('2026-09-18T17:30:00Z')});await page.goto(origin+'/report/');await page.waitForFunction(()=>!document.getElementById('destination-search').disabled);assert.equal(await page.locator('.report-section-index').count(),0);
await page.locator('#destination-search').fill('Miami');await page.locator('#destination-search').press('ArrowDown');await page.locator('#destination-search').press('Enter');
async function settled(){await page.waitForFunction(()=>document.getElementById('report-sheet').getAttribute('aria-busy')==='false')}
await settled();
async function unchanged(){assert.equal(await page.locator('.report-text').textContent(),bodyText);assert.deepEqual(await page.locator('.source-dates p').allTextContents(),dates.map(s=>s.label+': '+s.date));assert.equal(await page.locator('#report-meta time').getAttribute('datetime'),'2026-09-18T16:10:00Z');checks++}
await unchanged();assert.equal(await page.locator('.report-topic h3').count(),6);assert.equal(await page.getByRole('navigation',{name:'In this report'}).count(),1);
const nav=page.getByRole('navigation',{name:'In this report'});await nav.getByRole('link',{name:'Chlorophyll',exact:true}).focus();await page.keyboard.press('Enter');assert.equal(await page.evaluate(()=>document.activeElement.id),'report-topic-1');assert.equal(new URL(page.url()).hash,'');
const bounds=await page.locator('#report-topic-1').boundingBox();assert.ok(bounds.y>=0&&bounds.y<1000);await unchanged();
assert.ok(await page.locator('.skip-link').evaluate(e=>e.getBoundingClientRect().bottom<=0), 'Unfocused skip link stays outside viewport');await page.evaluate(()=>scrollTo(0,0));
await page.screenshot({path:path.join(evidence,`sections-${width}.png`),fullPage:true});
await page.evaluate(()=>document.documentElement.style.fontSize='200%');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(evidence,`sections-${width}-text200.png`),fullPage:true});await page.evaluate(()=>document.documentElement.style.fontSize='');
for(const sample of [text.replaceAll('\n','\r\n'), 'Unknown title\n28.40 °C; 0.023 mg/m³.\nCurrents\nThis is inside the same paragraph, not a heading.\n', 'Currents\n0.4 m/s.\n\nCurrents\nUnavailable — not zero.\n']){bodyText=sample;await page.locator('#refresh-report').click();await settled();await unchanged();if(sample.startsWith('Unknown')){assert.equal(await page.locator('.report-topic').count(),0);assert.equal(await page.locator('.report-section-index').count(),0)}else{const ids=await page.locator('.report-topic h3').evaluateAll(es=>es.map(e=>e.id));assert.equal(new Set(ids).size,ids.length)}}
unavailable=true;await page.locator('#refresh-report').click();await settled();assert.equal(await page.locator('.report-section-index,.report-topic,.report-text').count(),0);assert.deepEqual(errors,[]);await context.close();console.log(`${width}px: exact text/source/date preservation, semantic sections, focus navigation, 200% text, CRLF, unknown/duplicate headings and error cleanup passed`)}console.log(`PASS: ${checks} exact text/provenance comparisons`)}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
